name: .NET Core CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.404'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the solution
      - name: Build the solution
        run: dotnet build --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build # Ensures this job only runs after the build job completes
    steps:
      # Check out the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.404'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Run unit tests
      - name: Run Unit Tests
        run: dotnet test --configuration Release --no-build --verbosity normal
