name: .NET Core CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.404'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the solution
      - name: Build the solution
        run: dotnet build --configuration Release

    outputs:
      # Pass the build artifact directory to the next job
      artifact-path: ${{ steps.build.outputs.artifact-path }}

  test:
    runs-on: ubuntu-latest
    needs: build # Ensure this job runs only after the build job finishes
    steps:
      # Check out the code from GitHub (again, required for a separate job)
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.404'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Run unit tests
      - name: Run Unit Tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      # Run Architecture Tests
      - name: Run Architecture Tests
        run: dotnet test SCMS.ArchitectureTests/SCMS.ArchitectureTests.csproj --configuration Release --no-build --verbosity normal
