name: .NET Core CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.404'

      - name: Restore dependencies
        run: dotnet restore

      - name: Clean solution
        run: dotnet clean SupplyChainManagementSystem.sln

      - name: Build the solution
        run: dotnet build --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.404'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run Unit and Architecture Tests on Solution
        run: dotnet test SupplyChainManagementSystem.sln --configuration Release --no-build --verbosity normal
